name: Featured
favicon: null
layout_spectrum: 0.02684
typography_spectrum: 0.20039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#33cc66'
    - '#3367fe'
    - '#060606'
    - '#c0c0c0'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
