name: Featured
favicon: null
layout_spectrum: 0.7435830938629806
typography_spectrum: 0.4231491575483233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.271585964364931
  lightness: 0.6249089997727424
  saturation: 0.02778603369370103
  rhythmicContrast: 0.6336536156013608
purpose: []
